# Gopkg.toml

[[ constraint ]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[ constraint ]]
  branch = "master"
  name = "github.com/spf13/viper"

[[ constraint ]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[ constraint ]]
  branch = "master"
  name = "github.com/jeromer/syslogparser"

[[ constraint ]]
  branch = "master"
  name = "github.com/go-sql-driver/mysql"

[[ constraint ]]
  branch = "master"
  name = "k8s.io/api"

[[ constraint ]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[ constraint ]]
  branch = "master"
  name = "k8s.io/client-go"

[[ constraint ]]
  name = "gopkg.in/go-playground/validator.v9"
  branch = "v9"

[[ constraint ]]
  branch = "master"
  name = "github.com/aws/aws-sdk-go"

# [[ constraint ]]
  # name = "golang.org/x/crypto"

# [[ constraint ]]
  # name = "gopkg.in/src-d/go-git.v4"

# [[ constraint ]]
  # name = "github.com/go-playground/jsonschema"

[prune]
  go-tests = true
  unused-packages = true
